### ISSUE TITLE
Test SDR - SDR Functionality

### ISSUE THREAD

**Issue by jaidenfe** [jaidenfe/SDR_PHY_COM#6]
**Task** 
Running the SDR - SDR Functionality Test will ensure the _queue_len_framer_source_b_ (#1) and the _queue_len_deframer_sink_b_ (#3) blocks can operate simultaneously and with the expected functionality. The criteria that must be met is listed below: 
- [ ] The SDR can properly frame a packet
- [ ] The SDR can properly recognize a packet within noise
- [ ] The SDR only adds potential packets to the receive queue
- [ ] The SDR can transmit and receive simultaneously 
- [ ] The SDR operates at 9600 baud
